#!/usr/bin/env bash
#
# Join 360-degree INSV files into a single MP4
#

set -euo pipefail

#######################################################
# Self test
#######################################################
err() {
  echo -e "$*" >&2
  exit 1
}

self_test() {
  # check if MediaSDKTest is available
  command -v MediaSDKTest >/dev/null || \
    err "Error: MediaSDKTest is not available"

  # check if ffmpeg is available
  command -v ffmpeg >/dev/null || \
    err "Error: ffmpeg is not available"

  # check if exiftool is available
  command -v exiftool >/dev/null || \
    err "Error: exiftool is not available"

  # check if bc is available
  command -v bc >/dev/null || \
    err "Error: bc is not available"

  # check if exiftool version is 12.40 or later
  exiftool_ver="$(exiftool -ver | cut -d. -f1,2)"
  if [ "$(echo "${exiftool_ver} >= 12.40" | bc)" -eq 0 ]; then
    err "Error: exiftool version 12.40 or later is required"
  fi

}

join_insv() {

  if [ "$#" -lt 3 ]; then
    echo "Usage: ${FUNCNAME[0]} is_57k outfile infile1 [infile2 ...]"
    exit 1
  fi

  self_test

  local is_57k=$1
  local outfile="$2"
  shift 2

  local tmpfile="${outfile}"_tmp_.mp4
  local file_list
  file_list="$(mktemp --suffix="_list.txt" --tmpdir="$(pwd)")"

  rm -rf "${file_list}" "${tmpfile}"

  if ${is_57k}; then
    if [ $(( $# % 2 )) -ne 0 ]; then
      err "Error: 5.7K mode requires even number of files"
    fi

    while [ $# -gt 0 ]; do
      local left_eye="$1"
      local right_eye="$2"
      shift 2

      MediaSDKTest -inputs "$left_eye" "$right_eye" -output "${left_eye}.mp4" \
        -enable_directionlock -enable_flowstate -enable_denoise
      echo "file ${left_eye}.mp4" >> "${file_list}"
    done
  else
    for v in "$@"; do
      MediaSDKTest -inputs "$v" -output "${v}.mp4" \
        -enable_directionlock -enable_flowstate -enable_denoise
      echo "file ${v}.mp4" >> "${file_list}"
    done
  fi

  ffmpeg -safe 0 \
    -f concat \
    -i "${file_list}" \
    -vcodec copy \
    -acodec copy \
    -f mp4 "$tmpfile"

  exiftool -XMP-GSpherical:Spherical="true" \
    -XMP-GSpherical:Stitched="true" \
    -XMP-GSpherical:ProjectionType="equirectangular" \
    -XMP-GSpherical:StereoMode="mono" \
    -api largefilesupport=1 \
    "$tmpfile" \
    -o "$outfile"
}

usage() {
>&2 cat << EOF
Usage: ${0}
    [ -H | --is_57k ]
    [ -o | --output outfile ]
    [ -h | --help ]
    <infile> [infiles]
EOF
}

############################
# CLI entrypoint
############################
cli() {
  local is_57k=false
  local outfile=''

  args=$(getopt -a -o Ho:h --long is_57k,output:,help -- "$@")

  eval set -- "${args}"

  while :
  do
    case "$1" in
      -H | --is_57k) is_57k=true ; shift ;;
      -h | --help) usage ; exit 0 ;;
      -o | --output) outfile="$2" ; shift 2 ;;
      --) shift; break ;;
      *) >&2 echo "Unsupported optoin: $1"
         usage ; exit 1 ;;
    esac
  done

  [ -z "$outfile" ] && err "Error: [-o | --output] outfile is missing"

  [[ $# -eq 0 ]] && { usage; exit 1; }

  join_insv ${is_57k} "$outfile" "$@"

}

cli "$@"